# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c2776938e6478bbc0f1b83a68d1bf469d166861b0f35c11f2271987f10f8108719e6d5e996cd5e4951cce11d09dd43f6d5d35aff3ff8ca4f0c53fe94a811996

test:
  secret_key_base: 222092f2c4a4c6fbaa000edc5954bfa89de4a66bb8a0bcbb397b79b73b441de62ab28077dee6fde16e8e99cb3c1830a33814a7b695fea14f2dd24c2a8211a48a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
